### ISSUE TITLE
Link for Lena Herrmann's JavaScript highlighter is broken

### ISSUE THREAD

**Issue by rahilsh** [karlseguin/the-little-redis-book#41]
Link to `Lena Herrmann's JavaScript highlighter` - http://lenaherrmann.net/2010/05/20/javascript-syntax-highlighting-in-the-latex-listings-package is broken

**Comment by karlseguin** [comment]
Thanks. I removed the link as I couldn't find an updated one.

**Comment by rahilsh** [comment]
No problem
